# Generated by Django 4.2.1 on 2023-05-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='owner',
            new_name='user',
        ),
    ]
